-- 코드를 입력하세요
-- 세단 또는 suv
-- 2022-11-01 ~ 2022-11-30 까지 대여 가능
-- 30일간의 대여 금액 50 ~ 200 미만
-- 자동차 ID, 자동차 종류, 대여 금액
-- 대여 금액 기준 내림차순
-- 같은 경우 자동차 종류 기준 오름차순
-- 같은 경우 자동차 ID 기준 내림차순
SELECT 
C.CAR_ID AS CAR_ID,
C.CAR_TYPE AS CAR_TYPE,
ROUND(C.DAILY_FEE * 30 * (100 - P.DISCOUNT_RATE)/100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON C.CAR_TYPE = P.CAR_TYPE
WHERE C.CAR_TYPE IN ('세단', 'SUV')
AND C.CAR_ID NOT IN (SELECT CAR_ID
                    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                    WHERE END_DATE >= '2022-11-01' AND START_DATE <= '2022-11-30')
AND P.DURATION_TYPE	LIKE '30%'
GROUP BY C.CAR_ID
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID
